apiVersion: v1
kind: Secret
metadata:
    name: pluto-secrets
    namespace: media
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:8lttAVzWw/jJ8qZA5M1kyF9KOg==,iv:LVZvUYsUzseEjXZCGtUsUA248QWOq4oU7ru7IfKSSy4=,tag:0Qoj32Kzi/tuBLGdbULBNg==,type:str]
    password: ENC[AES256_GCM,data:5g4Mnb/vSN2Pev3Fv8qCsiGLdA==,iv:vVMdg9XUW2m38R4saz0mumeHLnO51ATFGcYn5y3lL1w=,tag:1R5vlga2bD4EZCnUBRzwbg==,type:str]
sops:
    age:
        - recipient: age16xrcrw9c0qjdlkzhj5y52ylg5jyueplkc2lkperujk42rwmdg97s243phc
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWkVYTzV5Ni9lMGFGdS9S
            UVJsMWQ4UHJ6c0tlQmFSc1hDR0JjaWhuNkVnClFzUC9Wa21GUUFtYW93Rkw0RlVO
            ZllOQ1M2d1RxcVQycWlHQkgwMUdPTDAKLS0tIHZ5Ri85cFZLcnVyRXArY2FIbDNN
            VlJreU9EQmZoL2VrZFdHRVFkZThSVHcK6O9J1c1sQNbU0ESbe9TO6j9OgB6boI/7
            JPTLpb0CrzCweSxo6aDxRrSb+dqhP8Mxt/qeU1MB77Lj6ssRfnXskQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-01T18:02:34Z"
    mac: ENC[AES256_GCM,data:thhamc+HZuQEGVyNzAqqy3jZcc4KtqlMoN3EnlDq/hLL2bSAzH9wy0XU5+ABxPznyAKR0dgLUC8t9ef5cWk7S0eEPzOIsF+Mdv1z9fxA6NWjl5BDBW52pE3AQT5xYUYbNccEDysdrw+jf3Sazzln9Km1c2aWu52ej3UE1H4q8YU=,iv:PmqkGOkDc5KQyFtcPH98pUJ6bluKD/hxeLkQKHKUJFU=,tag:qnfpve6Eva4OgVLdTlBt0g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
