apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-dispatcharr
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-simple
  resources:
    requests:
      storage: 10Gi
