apiVersion: v1
kind: Namespace
metadata:
  name: media
  annotations:
    # Enable privileged movers for VolSync to handle file ownership changes
    # This allows CHOWN, FOWNER, and DAC_OVERRIDE capabilities needed for syncthing
    volsync.backube/privileged-movers: "true"
