apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eplustv
  namespace: live
  labels:
    app: eplustv
spec:
  serviceName: eplustv-headless
  replicas: 1
  selector:
    matchLabels:
      app: eplustv
  template:
    metadata:
      labels:
        app: eplustv
        streaming-stack: "true"
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: eplustv
          image: tonywagner/eplustv:v4.15.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
              name: http
          env:
            - name: TZ
              value: "America/Chicago"
            - name: ESPN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eplustv-secrets
                  key: espn_username
            - name: ESPN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eplustv-secrets
                  key: espn_password
            - name: FLOSPORTS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: eplustv-secrets
                  key: flosports_username
            - name: FLOSPORTS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: eplustv-secrets
                  key: flosports_password
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi
          livenessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: config
              mountPath: /app/data
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app: eplustv
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn-simple
        resources:
          requests:
            storage: 5Gi
