---
# Longhorn RWX PVC for streaming media library (symlinks via Decypharr)
# Used by: Decypharr (creates symlinks), Sonarr/Radarr (organize), 
#          Plex (reads + serves streaming content via Intel QSV GPU transcoding)
# Architecture: Decypharr creates symlinks pointing to /mnt/dfs (RealDebrid cache)
#              Sonarr/Radarr organize those symlinks into proper folder structure
#              Plex aggregates this library with /mnt/media (permanent library) and transcodes
# Note: Using Longhorn RWX for HA - share-manager pods provide NFSv4 access
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-streaming-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany  # RWX: Multiple pods can read/write simultaneously
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 10Gi  # Quota for Sonarr disk space checks - actual usage minimal (DFS-backed via Debrid symlinks)
