---
# Longhorn RWX PVC for streaming media library (symlinks)
# Used by: Decypharr (creates symlinks), Sonarr/Radarr (organize), 
#          Plex (reads + serves), ClusterPlex (transcodes)
# Architecture: Decypharr creates symlinks pointing to /mnt/dfs (RealDebrid cache)
#              Sonarr/Radarr organize those symlinks into proper folder structure
#              Plex aggregates this library with /mnt/media (permanent library)
#              ClusterPlex workers read streaming content for GPU transcoding
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-streaming-media
  namespace: media
spec:
  accessModes:
    - ReadWriteMany  # RWX: Multiple pods can read/write simultaneously
  storageClassName: longhorn-rwx
  resources:
    requests:
      storage: 10Gi  # Size for symlinks + metadata (symlinks are just pointers)
