---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: decypharr-download
  namespace: media
  labels:
    app: decypharr-download
spec:
  serviceName: decypharr-download-headless
  replicas: 1
  selector:
    matchLabels:
      app: decypharr-download
  # PVC template for config storage
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app: decypharr-download
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn-simple
        resources:
          requests:
            storage: 1Gi
  template:
    metadata:
      labels:
        app: decypharr-download
        streaming-stack: "true"
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: false
        runAsUser: 0
      # Decypharr main container (NFS-only download mode - no FUSE)
      containers:
        - name: decypharr
          image: cy01/blackhole:beta
          imagePullPolicy: IfNotPresent
          command: ["/usr/bin/decypharr", "--config", "/config"]
          ports:
            - containerPort: 8282
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "America/Chicago"
            # Decypharr specific configs
            - name: LOG_LEVEL
              value: "INFO"
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 2000m
              memory: 2Gi
          volumeMounts:
            - name: config
              mountPath: /config
            - name: media-nfs
              mountPath: /mnt/media
      # Volumes
      volumes:
        - name: media-nfs
          persistentVolumeClaim:
            claimName: pvc-media-nfs
