apiVersion: v1
kind: PersistentVolume
metadata:
  name: clusterplex-dfs-nfs-pv
  labels:
    app.kubernetes.io/name: clusterplex-dfs-nfs
    app.kubernetes.io/part-of: clusterplex
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 10.43.160.244  # ClusterIP of clusterplex-nfs-server svc — routes to wherever pod runs (HA)
    path: /                  # NFSv4 root — fsid=0 export IS the /export/dfs directory
  mountOptions:
    - nfsvers=4      # Force NFSv4 — avoids NFSv3 portmapper/mountd complexity
    - noac           # Disable attribute caching (prevents staleness)
    - soft           # Fail fast if NFS server unreachable
    - timeo=10       # 1 second timeout (10 = 1s)
    - retrans=2      # Retry twice before failing
