apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-media-w3
  labels:
    app.kubernetes.io/part-of: clusterplex
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: media
    name: pvc-nfs-media-w3
  # Omit proto=tcp — PVE kernel 6.8 throws "Server address does not match proto= option"
  # with proto=tcp; NFSv3 auto-selects TCP without needing the explicit option.
  mountOptions:
    - nfsvers=3
    - soft
    - retrans=3
    - timeo=20
    - noresvport
  nfs:
    server: 192.168.1.29
    path: /mnt/user/media
