apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-transcode-w3
  labels:
    app.kubernetes.io/part-of: clusterplex
spec:
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: media
    name: clusterplex-transcode-w3
  # Accesses the same Longhorn RWX volume as clusterplex-transcode, via share-manager NFS.
  # PMS on w1 uses clusterplex-transcode (CSI); worker on w3 uses this NFS path to same data.
  # ClusterIP 10.43.24.173 is the share-manager Service for pvc-f33b650a-c40b-4a35-b43b-d3a3c3822b7b.
  # If this PVC is ever deleted and recreated, the ClusterIP will change — update this file.
  mountOptions:
    - nfsvers=4
    - soft
    - timeo=10
    - retrans=2
    - noac
  nfs:
    server: 10.43.24.173
    path: /pvc-f33b650a-c40b-4a35-b43b-d3a3c3822b7b
