apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clusterplex-transcode
  namespace: media
  labels:
    app.kubernetes.io/name: clusterplex-transcode
    app.kubernetes.io/part-of: clusterplex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-unraid
  resources:
    requests:
      storage: 200Gi
