apiVersion: batch/v1
kind: Job
metadata:
  name: volsync-rsync
  namespace: media
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: rsync
        image: alpine:3.18
        command:
          - /bin/sh
          - -c
          - |
            apk add --no-cache rsync
            mkdir -p /backup /primary
            rsync -a --delete /backup/ /primary/
        volumeMounts:
          - name: backup
            mountPath: /backup
          - name: primary
            mountPath: /primary
      volumes:
        - name: backup
          persistentVolumeClaim:
            claimName: pvc-sonarr-backup
        - name: primary
          persistentVolumeClaim:
            claimName: pvc-sonarr
