apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-controllers
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/homelab/infrastructure/controllers
  prune: true
  wait: true
  timeout: 2m
  dependsOn:
    - name: infrastructure-crds
  sourceRef:
    kind: GitRepository
    name: flux-system
  validation: client
