apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: infrastructure-storage
  namespace: flux-system
spec:
  interval: 1m
  path: ./clusters/homelab/infrastructure/storage
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
