apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: addresspools.metallb.io
spec:
  group: metallb.io
  scope: Namespaced
  names:
    kind: AddressPool
    plural: addresspools
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              addresses:
                type: array
                items:
                  type: string
              avoidBuggyIPs:
                type: boolean
              protocol:
                type: string
              bgpAdvertisements:
                type: array
                items:
                  type: object
              communities:
                type: array
                items:
                  type: string
          status:
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ipaddresspools.metallb.io
spec:
  group: metallb.io
  scope: Namespaced
  names:
    kind: IPAddressPool
    plural: ipaddresspools
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              addresses:
                type: array
                items:
                  type: string
              avoidBuggyIPs:
                type: boolean
              protocol:
                type: string
              bgpAdvertisements:
                type: array
                items:
                  type: object
              communities:
                type: array
                items:
                  type: string
          status:
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: l2advertisements.metallb.io
spec:
  group: metallb.io
  scope: Namespaced
  names:
    kind: L2Advertisement
    plural: l2advertisements
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              ipAddressPools:
                type: array
                items:
                  type: string
              nodeSelectors:
                type: array
                items:
                  type: object
          status:
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: communities.metallb.io
spec:
  group: metallb.io
  scope: Namespaced
  names:
    kind: Community
    plural: communities
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              value:
                type: string
          status:
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bgppeers.metallb.io
spec:
  group: metallb.io
  scope: Namespaced
  names:
    kind: BGPPeer
    plural: bgppeers
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              peerAddress:
                type: string
              peerASN:
                type: integer
              myASN:
                type: integer
          status:
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bfdprofiles.metallb.io
spec:
  group: metallb.io
  scope: Namespaced
  names:
    kind: BFDProfile
    plural: bfdprofiles
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              detectMultiplier:
                type: integer
              receiveInterval:
                type: string
              transmitInterval:
                type: string
          status:
            type: object
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: bgpadvertisements.metallb.io
spec:
  group: metallb.io
  scope: Namespaced
  names:
    kind: BGPAdvertisement
    plural: bgpadvertisements
  versions:
  - name: v1beta1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              ipAddressPools:
                type: array
                items:
                  type: string
          status:
            type: object
---
apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
