---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: profilarr
  namespace: media
  labels:
    app: profilarr
spec:
  serviceName: profilarr-headless
  replicas: 1
  selector:
    matchLabels:
      app: profilarr
  template:
    metadata:
      labels:
        app: profilarr
    spec:
      containers:
        - name: profilarr
          image: santiagosayshey/profilarr:v1.1.4
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6868
              name: http
          env:
            - name: TZ
              value: "America/Chicago"
            - name: PROFILARR_PORT
              value: "6868"
          resources:
            requests:
              cpu: 50m
              memory: 256Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 6868
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 6868
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 6868
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          volumeMounts:
            - name: config
              mountPath: /config
  # PVC template - creates PVC automatically per pod
  volumeClaimTemplates:
    - metadata:
        name: config
        labels:
          app: profilarr
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn-simple
        resources:
          requests:
            storage: 2Gi
