apiVersion: batch/v1
kind: CronJob
metadata:
  name: volume-fencing
  namespace: kube-system
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 2
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: volume-fencing
          restartPolicy: Never
          containers:
            - name: volume-fencing
              image: python:3.11-alpine
              imagePullPolicy: IfNotPresent
              command: ["/bin/sh", "-c"]
              args:
                - |
                  pip install --no-cache-dir kubernetes==29.0.0 >/tmp/pip.log 2>&1
                  python /scripts/fence.py
              env:
                - name: NODE_NOTREADY_SECONDS
                  value: "600"
                - name: STORAGE_CLASSES
                  value: "seaweedfs-storage"
                - name: DRY_RUN
                  value: "false"
              volumeMounts:
                - name: script
                  mountPath: /scripts
          volumes:
            - name: script
              configMap:
                name: volume-fencing-script
