---
# CSI Controller Deployment (leader-elected, replica count 1)
kind: Deployment
apiVersion: apps/v1
metadata:
  name: seaweedfs-controller
  namespace: seaweedfs
spec:
  selector:
    matchLabels:
      app: seaweedfs-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: seaweedfs-controller
    spec:
      priorityClassName: system-cluster-critical
      serviceAccountName: seaweedfs-controller-sa
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - seaweedfs-controller
              topologyKey: kubernetes.io/hostname
      containers:
        # SeaweedFS CSI Plugin (controller)
        - name: seaweedfs-csi-plugin
          image: chrislusf/seaweedfs-csi-driver:latest
          imagePullPolicy: IfNotPresent
          args:
            - --endpoint=$(CSI_ENDPOINT)
            - --filer=$(SEAWEEDFS_FILER)
            - --driverName=$(DRIVER_NAME)
            - --components=controller
            - --attacher=true
          env:
            - name: CSI_ENDPOINT
              value: unix:///var/lib/csi/sockets/pluginproxy/csi.sock
            - name: SEAWEEDFS_FILER
              # Point to seaweedfs filer service (deployed in seaweedfs namespace)
              value: "seaweedfs-filer-client.seaweedfs:8888"
            - name: DRIVER_NAME
              value: "seaweedfs-csi-driver"
          livenessProbe:
            httpGet:
              path: /healthz
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources: {}

        # CSI Provisioner (handles PVC -> PV creation)
        - name: csi-provisioner
          image: registry.k8s.io/sig-storage/csi-provisioner:v3.5.0
          imagePullPolicy: IfNotPresent
          args:
            - --csi-address=$(ADDRESS)
            - --leader-election
            - --leader-election-namespace=seaweedfs
            - --http-endpoint=:9809
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          ports:
            - containerPort: 9809
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz/leader-election
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources: {}

        # CSI Resizer (handles volume expansion)
        - name: csi-resizer
          image: registry.k8s.io/sig-storage/csi-resizer:v1.8.0
          imagePullPolicy: IfNotPresent
          args:
            - --csi-address=$(ADDRESS)
            - --leader-election
            - --leader-election-namespace=seaweedfs
            - --http-endpoint=:9810
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          ports:
            - containerPort: 9810
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz/leader-election
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources: {}

        # CSI Attacher (handles VolumeAttachment lifecycle)
        - name: csi-attacher
          image: registry.k8s.io/sig-storage/csi-attacher:v4.3.0
          imagePullPolicy: IfNotPresent
          args:
            - --csi-address=$(ADDRESS)
            - --leader-election
            - --leader-election-namespace=seaweedfs
            - --http-endpoint=:9811
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          ports:
            - containerPort: 9811
              name: healthz
          livenessProbe:
            httpGet:
              path: /healthz/leader-election
              port: healthz
            initialDelaySeconds: 10
            timeoutSeconds: 3
            periodSeconds: 60
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources: {}

        # Liveness Probe
        - name: csi-liveness-probe
          image: registry.k8s.io/sig-storage/livenessprobe:v2.10.0
          imagePullPolicy: IfNotPresent
          args:
            - --csi-address=$(ADDRESS)
            - --http-endpoint=:9808
          env:
            - name: ADDRESS
              value: /var/lib/csi/sockets/pluginproxy/csi.sock
          ports:
            - containerPort: 9808
              name: livenessprobe
          volumeMounts:
            - name: socket-dir
              mountPath: /var/lib/csi/sockets/pluginproxy/
          resources: {}

      volumes:
        - name: socket-dir
          emptyDir: {}
