---
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: seaweedfs-csi-driver
  namespace: seaweedfs
spec:
  attachRequired: true
  podInfoOnMount: true
  requiresRepublish: false
  storageCapacity: false
