apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kadalu-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: kadalu
      sourceRef:
        kind: HelmRepository
        name: kadalu
        namespace: flux-system
      version: "*"
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    namespace:
      create: true
      name: kadalu