apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kadalu-operator
  namespace: flux-system
spec:
  interval: 1h
  chart:
    spec:
      chart: https://github.com/kadalu/kadalu/releases/latest/download/kadalu-helm-chart.tgz
      version: "0.8.0"