---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: seaweedfs-csi-driver
  namespace: seaweedfs-csi-driver
spec:
  interval: 1h
  chart:
    spec:
      chart: seaweedfs-csi-driver
      sourceRef:
        kind: HelmRepository
        name: seaweedfs-csi-driver
        namespace: seaweedfs-csi-driver
  values:
    seaweedfsFiler: "seaweedfs-filer.seaweedfs:8888"
    driver:
      logLevel: info
    
    # Increase timeouts for better failover handling
    node:
      kubeletRegistrationTimeout: "5m"
    
    # Add mount options for better resilience
    storageClass:
      seaweedFS:
        mountOptions:
          - "retry=3"
          - "connectTimeout=60s"
