apiVersion: apps/v1
kind: Deployment
metadata:
  name: volsync-controller-manager
  namespace: volsync
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - command:
            - /manager
          image: ghcr.io/backube/volsync:v0.8.2
          name: manager
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          resources: {}
      serviceAccountName: volsync-controller-manager
---
apiVersion: v1
kind: Namespace
metadata:
  name: volsync
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: volsync-controller-manager
  namespace: volsync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: volsync-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: volsync-manager-role
subjects:
  - kind: ServiceAccount
    name: volsync-controller-manager
    namespace: volsync
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: volsync-manager-role
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
