---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: longhorn-simple
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "2"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "best-effort"
  replicaAutoBalance: "least-effort"
  disableRevisionCounter: "true"
  dataEngine: "v1"
  # No node tag selector - allow all nodes with Longhorn
