apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: dispatcharr
  namespace: live
  labels:
    app: dispatcharr
spec:
  serviceName: dispatcharr-headless
  replicas: 1
  selector:
    matchLabels:
      app: dispatcharr
  template:
    metadata:
      labels:
        app: dispatcharr
        streaming-stack: "true"
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: false
        runAsUser: 0
      containers:
        - name: dispatcharr
          image: ghcr.io/dispatcharr/dispatcharr:v0.20.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9191
              name: http
          env:
            - name: TZ
              value: "America/Chicago"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9191
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9191
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
        labels:
          app: dispatcharr
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn-simple
        resources:
          requests:
            storage: 10Gi
