apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-media-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Ti
  storageClassName: nfs-unraid
  volumeName: pv-nfs-media
