apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-transcode-nfs
  namespace: media
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
  storageClassName: nfs-unraid
  volumeName: pv-nfs-transcode
