apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-prowlarr-backup
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  hostPath:
    path: /data/pods/prowlarr
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - backup
  claimRef:
    namespace: media
    name: pvc-prowlarr-backup
