apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-prowlarr-backup
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: ""
  volumeName: pv-prowlarr-backup
