apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prowlarr
  namespace: media
  labels:
    app: prowlarr
spec:
  serviceName: prowlarr-headless  # Links to headless service
  replicas: 0  # Start with 0 replicas (same as original deployment)
  selector:
    matchLabels:
      app: prowlarr
  # Use OnDelete to prevent automatic restarts during updates
  updateStrategy:
    type: OnDelete
  # Ordered pod management (wait for ready before starting next)
  podManagementPolicy: OrderedReady
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      # Node affinity: Prefer w1 (primary), allow w2 (backup) as failover
      affinity:
        nodeAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100  # Highest weight for primary node
              preference:
                matchExpressions:
                  - key: workload-priority
                    operator: In
                    values:
                      - primary
            - weight: 10   # Low weight for backup (only if primary unavailable)
              preference:
                matchExpressions:
                  - key: workload-priority
                    operator: In
                    values:
                      - backup
      # Tolerations: Allow scheduling on w2 despite PreferNoSchedule taint
      tolerations:
        - key: role
          operator: Equal
          value: backup
          effect: PreferNoSchedule
        # Faster failover: Evict after 30 seconds instead of default 5 minutes
        - key: node.kubernetes.io/unreachable
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 30
        - key: node.kubernetes.io/not-ready
          operator: Exists
          effect: NoExecute
          tolerationSeconds: 30
      containers:
        - name: prowlarr
          image: linuxserver/prowlarr@sha256:a82e6d95e0f41ec2383cdbfe89b35384b16bde22eebc8201b98bd9778c2e2062
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9696
              name: http
          env:
            - name: PUID
              value: "1000"
            - name: PGID
              value: "1000"
            - name: TZ
              value: "UTC"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /
              port: 9696
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /
              port: 9696
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /
              port: 9696
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 30
          volumeMounts:
            - name: config  # Matches volumeClaimTemplate name
              mountPath: /config
  # PVC template - creates PVC automatically per pod
  volumeClaimTemplates:
    - metadata:
        name: config  # Will create PVC: config-prowlarr-0
        labels:
          app: prowlarr
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: seaweedfs-storage
        resources:
          requests:
            storage: 2Gi
