# VolSync Syncthing ReplicationSource for Prowlarr primary node
# This syncs pvc-prowlarr (primary) with pvc-prowlarr-backup (backup)
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-primary
  namespace: media
spec:
  sourcePVC: pvc-prowlarr
  syncthing:
    serviceType: ClusterIP
    peers:
    - ID: 6LGG2UT-Q4JWQC4-DMIJNHV-C5R3B2A-NLPYAUA-GYTHKIG-FCYQMBU-TYVHMAT
      address: tcp://10.43.220.252:22000
      introducer: false
---
# VolSync Syncthing ReplicationSource for Prowlarr backup node
# This is the peer that syncs with the primary
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prowlarr-backup
  namespace: media
spec:
  sourcePVC: pvc-prowlarr-backup
  syncthing:
    serviceType: ClusterIP
    peers:
    - ID: ZLIWZ56-PT2PBY3-PP37XID-XEIUD6U-AR7DUMM-UJFKDSC-77XLUQ4-XAXBEQN
      address: tcp://10.43.119.34:22000
      introducer: false
