apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-dfs
  labels:
    app.kubernetes.io/name: pv-nfs-dfs
    app.kubernetes.io/part-of: plex
spec:
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: media
    name: pvc-nfs-dfs
  nfs:
    server: 10.43.160.244  # ClusterIP of plex-nfs-server svc — pinned, routes to NFS server pod (on w1/w2 for HA)
    path: /                  # NFSv4 root — fsid=0 export IS the /export/dfs directory
  mountOptions:
    - nfsvers=4      # Force NFSv4 — avoids NFSv3 portmapper/mountd complexity
    - noac           # Disable attribute caching (prevents staleness)
    - soft           # Fail fast if NFS server unreachable
    - timeo=10       # 1 second timeout (10 = 1s)
    - retrans=2      # Retry twice before failing
