apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-nfs-dfs
  namespace: media
  labels:
    app.kubernetes.io/name: pvc-nfs-dfs
    app.kubernetes.io/part-of: plex
spec:
  volumeName: pv-nfs-dfs
  accessModes:
    - ReadWriteMany
  storageClassName: ""  # Manual binding to PV
  resources:
    requests:
      storage: 100Gi
