---
# FUSE Producer Pod
# Tests whether a pod can create files in a Bidirectional hostPath volume
# and have those files visible on the host, then accessible to other pods
apiVersion: v1
kind: Pod
metadata:
  name: fuse-producer
  namespace: fuse-test
  labels:
    test: fuse-propagation
    role: producer
spec:
  # Force deployment to w2 (secondary storage node - safer for testing)
  nodeName: k3s-w2
  
  securityContext:
    runAsUser: 0
    runAsNonRoot: false
  
  containers:
  - name: fuse-creator
    image: alpine:3.19
    imagePullPolicy: IfNotPresent
    
    securityContext:
      privileged: true
      capabilities:
        add:
          - SYS_ADMIN
    
    command: ["/bin/sh", "-c"]
    args:
      - |
        #!/bin/sh
        set -x
        
        # Log startup
        echo "=== FUSE Producer Starting ==="
        date
        whoami
        pwd
        
        # Ensure mount point exists
        mkdir -p /mnt/dfs
        ls -la /mnt/dfs
        
        # Create initial marker file (proves we can write)
        TIMESTAMP=$(date +%s)
        echo "producer-started-${TIMESTAMP}" > /mnt/dfs/producer-marker.txt
        touch /mnt/dfs/.producer-ready
        
        echo "Initial /mnt/dfs contents:"
        ls -la /mnt/dfs/
        
        cat /mnt/dfs/producer-marker.txt
        
        # Keep the pod running so mount stays alive
        echo "=== Producer Ready, Keeping Alive ==="
        COUNT=0
        while true; do
          COUNT=$((COUNT + 1))
          echo "[$(date)] Producer alive (iteration $COUNT)"
          
          # Periodically update a log file (proves continuous access)
          echo "[$(date)] Heartbeat #$COUNT" >> /mnt/dfs/producer-heartbeat.log
          
          sleep 30
          done
    
    volumeMounts:
    - name: fuse-bridge
      mountPath: /mnt/dfs
      mountPropagation: Bidirectional
    
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 256Mi
  
  volumes:
  - name: fuse-bridge
    hostPath:
      path: /tmp/fuse-test-bridge
      type: DirectoryOrCreate
  
  restartPolicy: OnFailure
  
  # Tolerate storage node taints
  tolerations:
  - key: node.longhorn.io/storage
    operator: Equal
    value: enabled
    effect: NoSchedule
