---
# DFS Mounter DaemonSet
# Runs on all storage nodes (w1, w2) and GPU node (w3)
# Mounts Decypharr's FUSE-backed DFS via Samba (smbd) as kernel CIFS on host's /mnt/decypharr-dfs
# App pods access via hostPath volume with HostToContainer propagation (no privilege required)
# CIFS kernel client auto-reconnects when smbd restarts — no consumer pod restart needed
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: dfs-mounter
  namespace: media
  labels:
    app: dfs-mounter
spec:
  selector:
    matchLabels:
      app: dfs-mounter
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: dfs-mounter
    spec:
      hostPID: false
      hostNetwork: false   # Use pod network → CoreDNS resolves ClusterIP service names
      priorityClassName: system-node-critical
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              # Run on storage nodes (w1, w2) OR GPU nodes (w3)
              - matchExpressions:
                  - key: node.longhorn.io/storage
                    operator: In
                    values:
                      - enabled
              - matchExpressions:
                  - key: gpu
                    operator: In
                    values:
                      - "true"
      tolerations:
        # Storage nodes
        - key: node.longhorn.io/storage
          operator: Exists
          effect: NoSchedule
        # GPU nodes (if any)
        - key: gpu
          operator: Equal
          value: "true"
          effect: NoSchedule
      containers:
        - name: dfs-mounter
          image: alpine:3.19
          imagePullPolicy: IfNotPresent
          command: ["/bin/sh", "-c"]
          args:
            - |
              apk add --no-cache cifs-utils --quiet
              mkdir -p /mnt/decypharr-dfs
              while true; do
                # Check specifically for CIFS mount — NOT mountpoint -q which returns true
                # for the hostPath bind-mount itself, causing CIFS to never be attempted.
                if grep -q '/mnt/decypharr-dfs cifs' /proc/mounts 2>/dev/null; then
                  if ! timeout 3 ls /mnt/decypharr-dfs >/dev/null 2>&1; then
                    echo "CIFS mount stale, force-unmounting..."
                    umount -f /mnt/decypharr-dfs 2>/dev/null || umount -l /mnt/decypharr-dfs 2>/dev/null || true
                  fi
                fi
                # Mount CIFS if not already mounted.
                # CIFS kernel client auto-reconnects when smbd restarts — unlike NFS soft mounts
                # which become permanently stale and require a pod restart to recover.
                if ! grep -q '/mnt/decypharr-dfs cifs' /proc/mounts 2>/dev/null; then
                  echo "Mounting DFS via CIFS..."
                  mount -t cifs \
                    //decypharr-streaming-smb.media.svc.cluster.local/dfs \
                    /mnt/decypharr-dfs \
                    -o guest,uid=0,gid=0,file_mode=0755,dir_mode=0755,vers=3.0 \
                    && echo "DFS mounted via CIFS" || echo "Mount failed, retrying in 15s..."
                fi
                sleep 15
              done
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
          volumeMounts:
            - name: dfs-host
              mountPath: /mnt/decypharr-dfs
              mountPropagation: Bidirectional
      volumes:
        - name: dfs-host
          hostPath:
            path: /mnt/decypharr-dfs
            type: DirectoryOrCreate    # Created automatically if not present on the node
