apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-sonarr-primary
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-path
  hostPath:
    path: /data/pods/sonarr
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: role
              operator: In
              values:
                - primary
  claimRef:
    namespace: media
    name: pvc-sonarr
