apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-media
  labels:
    storage: nfs-unraid
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-unraid
  nfs:
    server: 192.168.1.29
    path: /mnt/user/media
    readOnly: true
