---
# ClusterIP Service for Decypharr Streaming SMB export (rclone-smb-server)
# DaemonSet pods mount this service to access the DFS CIFS export
apiVersion: v1
kind: Service
metadata:
  name: decypharr-streaming-smb
  namespace: media
  labels:
    app: decypharr-streaming
spec:
  type: ClusterIP
  selector:
    app: decypharr-streaming
  ports:
    - name: smb
      port: 445
      targetPort: 445
      protocol: TCP
