---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-logs
  namespace: victoria-logs
spec:
  interval: 1h
  chart:
    spec:
      chart: victoria-logs-single
      version: "0.x.x"
      sourceRef:
        kind: HelmRepository
        name: victoria-logs
        namespace: victoria-logs
  values:
    server:
      persistentVolume:
        enabled: true
        size: 10Gi
        storageClassName: longhorn-simple
        mountPath: /victorialogs-data
      
      vmui:
        enabled: true
      
      extraArgs:
        retentionPeriod: 4d
        storageDataPath: /victorialogs-data
      
      resources:
        requests:
          memory: 512Mi
          cpu: 250m
        limits:
          memory: 1Gi
          cpu: 500m
  
  postRenderers:
    - kustomize:
        patchesJson6902:
          - target:
              group: apps
              version: v1
              kind: StatefulSet
              name: victoria-logs-victoria-logs-single-server
              namespace: victoria-logs
            patch:
              - op: add
                path: /spec/template/spec/nodeSelector
                value:
                  node.longhorn.io/create-default-disk: "true"
              - op: add
                path: /spec/template/spec/tolerations
                value:
                  - key: node.longhorn.io/storage
                    operator: Equal
                    value: enabled
                    effect: NoSchedule
