apiVersion: batch/v1
kind: CronJob
metadata:
  name: descheduler
  namespace: kube-system
spec:
  schedule: "*/5 * * * *"  # Run every 5 minutes - checks for pods on non-preferred nodes
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: descheduler
        spec:
          serviceAccountName: descheduler
          restartPolicy: Never
          containers:
            - name: descheduler
              image: registry.k8s.io/descheduler/descheduler:v0.30.0
              command:
                - "/bin/descheduler"
              args:
                - "--policy-config-file=/policy/policy.yaml"
                - "--v=3"
              volumeMounts:
                - name: policy
                  mountPath: /policy
              resources:
                requests:
                  cpu: 50m
                  memory: 64Mi
                limits:
                  cpu: 200m
                  memory: 128Mi
          volumes:
            - name: policy
              configMap:
                name: descheduler-policy
