apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha2"
    kind: "DeschedulerPolicy"
    profiles:
      - name: default
        pluginConfig:
          - name: "RemovePodsViolatingNodeAffinity"
            args:
              nodeAffinityType:
                - "preferredDuringSchedulingIgnoredDuringExecution"
          - name: "DefaultEvictor"
            args:
              evictFailedBarePods: false
              evictLocalStoragePods: false
              evictSystemCriticalPods: false
              nodeFit: true
        plugins:
          deschedule:
            enabled:
              - "RemovePodsViolatingNodeAffinity"
