apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: seaweedfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: seaweedfs-csi-driver
parameters:
  # 010: 1 replica on different rack (matches topology.kubernetes.io/rack labels)
  replication: "010"
  # Base path for buckets in filer - apps write to /buckets/<pvc-name>
  path: /buckets
  # Disk type preference (hdd or ssd)
  diskType: "hdd"
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
