apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr-backup
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: pv-sonarr-backup
