apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: seaweedfs-ha
