apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  namespace: media
  labels:
    app: sonarr
spec:
  serviceName: sonarr-headless  # Links to headless service
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  template:
    metadata:
      labels:
        app: sonarr
        streaming-stack: "true"  # Label for pod affinity grouping
    spec:
      securityContext:
        fsGroup: 1000
        runAsNonRoot: false
        runAsUser: 0
      # Volumes: NFS shares from Unraid and streaming media
      volumes:
        - name: media-nfs
          persistentVolumeClaim:
            claimName: pvc-media-nfs
        - name: streaming-media
          persistentVolumeClaim:
            claimName: pvc-streaming-media
        - name: dfs
          hostPath:
            path: /mnt/dfs  # FUSE mount propagated from decypharr-streaming to host /mnt/dfs
            type: DirectoryOrCreate
      containers:
        - name: sonarr
          image: linuxserver/sonarr:4.0.16
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8989
              name: http
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/Chicago"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /ping
              port: 8989
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 8989
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          startupProbe:
            httpGet:
              path: /ping
              port: 8989
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 60  # 10 minutes total for first startup with migrations
          volumeMounts:
            - name: config  # Matches volumeClaimTemplate name
              mountPath: /config
            - name: media-nfs  # Unraid media library
              mountPath: /mnt/media
            - name: dfs  # FUSE mount received from host via HostToContainer (MS_SLAVE) propagation
              mountPath: /mnt/dfs
              mountPropagation: HostToContainer
            - name: streaming-media  # Symlinks and streamed content
              mountPath: /mnt/streaming-media
  # PVC template - creates PVC automatically per pod
  volumeClaimTemplates:
    - metadata:
        name: config  # Will create PVC: config-sonarr-0
        labels:
          app: sonarr
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: longhorn-simple  # Custom StorageClass without node selectors
        resources:
          requests:
            storage: 5Gi
