# VolSync Syncthing ReplicationSource for Sonarr primary node
# This syncs pvc-sonarr (primary) with pvc-sonarr-backup (backup)
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-primary
  namespace: media
spec:
  sourcePVC: pvc-sonarr
  syncthing:
    serviceType: ClusterIP
    peers:
    - ID: BIK4775-O4DG3X7-N7GB7U7-XKXVWIT-RLBFZYA-O2GFGBQ-RPA3Q2P-A25WNQR
      address: tcp://10.43.163.112:22000
      introducer: false
    moverSecurityContext:
      capabilities:
        add:
          - CHOWN
          - FOWNER
          - DAC_OVERRIDE
---
# VolSync Syncthing ReplicationSource for Sonarr backup node
# This is the peer that syncs with the primary
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: sonarr-backup
  namespace: media
spec:
  sourcePVC: pvc-sonarr-backup
  syncthing:
    serviceType: ClusterIP
    peers:
    - ID: FRLLMNU-EOC2JSF-PMB5KWD-JCYA5DA-RN5MKP4-YPKEFMO-6XWFGNN-6AMJLAS
      address: tcp://10.43.76.239:22000
      introducer: false
    moverSecurityContext:
      capabilities:
        add:
          - CHOWN
          - FOWNER
          - DAC_OVERRIDE
